

services:
  db:
    image: postgres:13
    container_name: social_db
    environment:
      POSTGRES_DB: social_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d social_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: social_backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/social_db
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: social_frontend
    expose:
      - "8000"
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_started

  nginx:
    image: nginx:alpine
    container_name: social_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/server.crt:/etc/ssl/certs/server.crt:ro
      - ./certs/server.key:/etc/ssl/private/server.key:ro
    depends_on:
      - frontend
